; Nur I2C-Scan – Adressen am Port A (bzw. CatM Port A) ermitteln
; Flashen: pio run -t upload
; Serial Monitor: pio device monitor -b 115200

[env:cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
upload_port = /dev/ttyACM0

build_flags =
    -DESP32S3
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
